# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18e42364361e36542be437dab329a58ef0143233813a7a884a5dab34616a06afbf0f622569453e9a2488270575e117ffaaf2cab02ae5d0252ac21ed447629096

test:
  secret_key_base: 336f3a27f4297f42f73876dba9e53ac04861c148d979188e776927f9984baa6495b7c66a33523e0b6546a0c4e944a8749a9c251963b606d5b76b3bc657c1507f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
